# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Pipeline-test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_048ad2cdf5a84a088036251a8e30af42 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e2923f9331e44dadbf4186ba46ef6956 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_048ad2cdf5a84a088036251a8e30af42 }}/xxx:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Pipeline-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_40c07b68367b43e3935f8db9a2a53718 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_048ad2cdf5a84a088036251a8e30af42 }}/xxx:${{ github.sha }}'